### ISSUE TITLE
MainScreen always defaults to IdolManagement

### ISSUE THREAD

**Issue by sr229** [ClarityMoe/Lovewing#13]
Probs needs investigation why is it the default view and not HomeWedge

**Comment by noud02** [comment]
should've been fixed in my last commit

**Comment by sr229** [comment]
we would need to investigate further though before we can close this

**Comment by apap04** [comment]
do you mean that when the game starts up, it's at the Idol screen instead of Home? 
If so, it doesn't happen to me.

**Comment by sr229** [comment]
fixed on latest commit by @noud02 last Monday
