### ISSUE TITLE
Visual Tests Configuration does not work

### ISSUE THREAD

**Issue by sr229** [ClarityMoe/Lovewing#24]
After a few builds in the current commit hash, the Visual Tests Configuration does not work on current client.

**Comment by jorolf** [comment]
that is a framework issue
https://github.com/ppy/osu-framework/blob/4489791c8f1299ee4cc045454f76bfd34940aabf/osu.Framework/Testing/TestBrowser.cs#L61

**Comment by jorolf** [comment]
change that to Lovewing and it loads them

**Comment by sr229** [comment]
Confirmed to work on ``/dev``

Closing
